// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: mwmr/mwmr.proto

package mwmr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key uint64 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mwmr_mwmr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mwmr_mwmr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_mwmr_mwmr_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Time  int64  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Cid   int64  `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mwmr_mwmr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_mwmr_mwmr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_mwmr_mwmr_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetReply) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GetReply) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint64 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Time  int64  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Cid   int64  `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mwmr_mwmr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mwmr_mwmr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_mwmr_mwmr_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *SetRequest) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SetRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SetRequest) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

type SetACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Applied bool `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
}

func (x *SetACK) Reset() {
	*x = SetACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mwmr_mwmr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetACK) ProtoMessage() {}

func (x *SetACK) ProtoReflect() protoreflect.Message {
	mi := &file_mwmr_mwmr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetACK.ProtoReflect.Descriptor instead.
func (*SetACK) Descriptor() ([]byte, []int) {
	return file_mwmr_mwmr_proto_rawDescGZIP(), []int{3}
}

func (x *SetACK) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

var File_mwmr_mwmr_proto protoreflect.FileDescriptor

var file_mwmr_mwmr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x77, 0x6d, 0x72, 0x2f, 0x6d, 0x77, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6d, 0x77, 0x6d, 0x72, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22,
	0x5a, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x06, 0x53,
	0x65, 0x74, 0x41, 0x43, 0x4b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x32,
	0x64, 0x0a, 0x04, 0x4d, 0x57, 0x4d, 0x52, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x12, 0x10, 0x2e, 0x6d, 0x77, 0x6d, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x77, 0x6d, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x12, 0x10, 0x2e, 0x6d, 0x77, 0x6d, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x77, 0x6d, 0x72, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x43, 0x4b, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x43, 0x53, 0x35, 0x39, 0x38, 0x46, 0x54,
	0x53, 0x2d, 0x57, 0x61, 0x72, 0x6d, 0x75, 0x70, 0x2f, 0x6d, 0x77, 0x6d, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mwmr_mwmr_proto_rawDescOnce sync.Once
	file_mwmr_mwmr_proto_rawDescData = file_mwmr_mwmr_proto_rawDesc
)

func file_mwmr_mwmr_proto_rawDescGZIP() []byte {
	file_mwmr_mwmr_proto_rawDescOnce.Do(func() {
		file_mwmr_mwmr_proto_rawDescData = protoimpl.X.CompressGZIP(file_mwmr_mwmr_proto_rawDescData)
	})
	return file_mwmr_mwmr_proto_rawDescData
}

var file_mwmr_mwmr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mwmr_mwmr_proto_goTypes = []interface{}{
	(*GetRequest)(nil), // 0: mwmr.GetRequest
	(*GetReply)(nil),   // 1: mwmr.GetReply
	(*SetRequest)(nil), // 2: mwmr.SetRequest
	(*SetACK)(nil),     // 3: mwmr.SetACK
}
var file_mwmr_mwmr_proto_depIdxs = []int32{
	0, // 0: mwmr.MWMR.GetPhase:input_type -> mwmr.GetRequest
	2, // 1: mwmr.MWMR.SetPhase:input_type -> mwmr.SetRequest
	1, // 2: mwmr.MWMR.GetPhase:output_type -> mwmr.GetReply
	3, // 3: mwmr.MWMR.SetPhase:output_type -> mwmr.SetACK
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mwmr_mwmr_proto_init() }
func file_mwmr_mwmr_proto_init() {
	if File_mwmr_mwmr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mwmr_mwmr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mwmr_mwmr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mwmr_mwmr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mwmr_mwmr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mwmr_mwmr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mwmr_mwmr_proto_goTypes,
		DependencyIndexes: file_mwmr_mwmr_proto_depIdxs,
		MessageInfos:      file_mwmr_mwmr_proto_msgTypes,
	}.Build()
	File_mwmr_mwmr_proto = out.File
	file_mwmr_mwmr_proto_rawDesc = nil
	file_mwmr_mwmr_proto_goTypes = nil
	file_mwmr_mwmr_proto_depIdxs = nil
}
